name: "Hola mundo"

on:
    push:
        branches: [main]

jobs:
    deploy-codigofacilito:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Hacemos pull del codigo"
            - run: echo "Correr migraciones"
            - run: echo "Generar binario"
            - run: echo "Publicar version"
            - run: echo "publicar version en master"
            - run: echo "Hacemos deploy en produccion -> main"
            