name: "Hola mundo"

on:
    push:
        branches: [main]

jobs:
    deploy-codigofacilito:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Hacemos pull del codigo"
            - run: exho "Correr migraciones"
            - run: echo "Generar binario"
            - run: echo "Publicar version"
            